trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  testProjects: 'tests/**/*.csproj'
  sourceProjects: 'src/**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: GitVersion@5
  displayName: GitVersion
  inputs:
    updateAssemblyInfo: true
    preferBundledVersion: false
    configFilePath: 'GitVersion.yml'

- task: DotNetCoreCLI@2
  displayName: '.NET Restore'
  inputs:
    command: 'restore'
    projects: |
     $(sourceProjects)
     $(testProjects)

- task: DotNetCoreCLI@2
  displayName: '.NET Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) /p:Version=$(GitVersion.NuGetVersion) --no-restore --output $(Build.ArtifactStagingDirectory)/app/src'
    versioningScheme: byBuildNumber
    projects: |
     $(sourceProjects)
     $(testProjects)

- task: DotNetCoreCLI@2
  displayName: '.NET Test'
  inputs:
    command: 'test'
    publishTestResults: true
    mergeTestResults: true
    failTaskOnFailedTests: true
    projects: $(testProjects)

- task: PublishBuildArtifacts@1
  displayName: ".NET Publish"
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/app
    ArtifactName: app